namespace VakilAI.Infrastructure.Storage;

using VakilAI.Application.Contracts;
using VakilAI.Domain.Repositories;
using VakilAI.Domain.ValueObjects;

/// <summary>
/// <see cref="IDeviceStore"/> backed by a simple asynchronous key/value preference pair
/// (on device: <c>Preferences.Get/Set</c>, in tests: a dictionary). Device identity is the one
/// value that must survive app updates, so it is written once and only overwritten deliberately.
/// </summary>
/// <remarks>Thread-safe: every read/write of the in-memory mirror happens under <c>_gate</c>.</remarks>
public sealed class DelegateDeviceStore(
    Func<string, Task<string?>> read,
    Func<string, string, Task> write,
    IRng rng) : IDeviceStore
{
    /// <summary>Preference key holding the stable device identifier.</summary>
    public const string DeviceIdKey = "vakil.device.id";

    /// <summary>Preference key holding the user's display name.</summary>
    public const string UserNameKey = "vakil.user.name";

    /// <summary>Length of the random part of a device id, in bytes (16 bytes = 32 hex chars).</summary>
    public const int DeviceIdEntropyBytes = 16;

    /// <summary>Prefix that marks an id generated by the app itself (not imported from a channel).</summary>
    public const string DeviceIdPrefix = "app-";

    private readonly object _gate = new();
    private string? _deviceId;
    private string? _userName;

    /// <inheritdoc />
    public async Task<DeviceId?> GetDeviceIdAsync()
    {
        lock (_gate)
        {
            if (_deviceId is not null)
            {
                return ToDeviceId(_deviceId);
            }
        }

        var raw = await read(DeviceIdKey).ConfigureAwait(false);
        lock (_gate)
        {
            _deviceId = raw;
        }

        return ToDeviceId(raw);
    }

    /// <inheritdoc />
    public async Task SaveDeviceIdAsync(DeviceId id)
    {
        ArgumentNullException.ThrowIfNull(id);
        if (!DeviceId.IsValid(id.Value))
        {
            throw new ArgumentException("Device id is empty or out of the allowed length range.", nameof(id));
        }

        var value = id.Value.Trim();
        await write(DeviceIdKey, value).ConfigureAwait(false);

        lock (_gate)
        {
            _deviceId = value;
        }
    }

    /// <inheritdoc />
    public async Task<string?> GetUserNameAsync()
    {
        lock (_gate)
        {
            if (_userName is not null)
            {
                return _userName;
            }
        }

        var raw = await read(UserNameKey).ConfigureAwait(false);
        var name = string.IsNullOrWhiteSpace(raw) ? null : raw.Trim();

        lock (_gate)
        {
            _userName = name;
        }

        return name;
    }

    /// <inheritdoc />
    public async Task SaveUserNameAsync(string name)
    {
        ArgumentNullException.ThrowIfNull(name);

        var value = name.Trim();
        await write(UserNameKey, value).ConfigureAwait(false);

        lock (_gate)
        {
            _userName = value;
        }
    }

    /// <summary>
    /// Read the stored device id, generating and persisting a new one
    /// (<c>app-</c> + 32 lowercase hex chars) when none exists yet.
    /// </summary>
    public async Task<DeviceId> GetOrCreateDeviceIdAsync()
    {
        var existing = await GetDeviceIdAsync().ConfigureAwait(false);
        if (existing is not null)
        {
            return existing;
        }

        var created = NewDeviceId();
        await SaveDeviceIdAsync(created).ConfigureAwait(false);
        return created;
    }

    /// <summary>Build a fresh, cryptographically random device id without persisting it.</summary>
    public DeviceId NewDeviceId() => new(DeviceIdPrefix + rng.NextHex(DeviceIdEntropyBytes));

    private static DeviceId? ToDeviceId(string? raw) =>
        DeviceId.IsValid(raw) ? new DeviceId(raw!.Trim()) : null;
}
